---
- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
      tags: a
    - name: uninstalling git
      yum: 
        name: git
        state: latest
      tags: b
    - name: start the web server
      service:
        name: httpd
        state: started
      tags: c
    - name: install httpd software
      yum: 
        name: httpd
        state: absent
      tags: d

